rss_keywords:
  - "Commerce Secretary"
  - "Commerce Department"
  - "Lutnick"
  - "Howard Lutnick"
  - "Department of Commerce"
  - "Secretary of Commerce"

api_keywords:
  - "Howard Lutnick"
  - "Department of Commerce"

rss_feeds:
  foxnews: https://feeds.foxnews.com/foxnews/latest
  wsj: https://feeds.a.dj.com/rss/RSSMarketsMain.xml
  washingtonpost: https://feeds.washingtonpost.com/rss/politics
  politico: https://rss.politico.com/politics-news.xml
  nytimes: https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
  bloomberg: https://feeds.bloomberg.com/politics/news.rss
  financialtimes: https://www.ft.com/?format=rss
  cnbc: https://www.cnbc.com/id/100003114/device/rss/rss.html
  cnn: http://rss.cnn.com/rss/cnn_topstories.rss
  abc: https://abcnews.go.com/abcnews/politicsheadlines
  bbc: http://feeds.bbci.co.uk/news/rss.xml
  usatoday: https://www.usatoday.com/rss/news/
  foxbusiness: https://feeds.foxbusiness.com/foxbusiness/latest
