rss_keywords:
  - "Commerce Secretary"
  - "Commerce Department"
  - "Lutnick"
  - "Howard Lutnick"
  - "Department of Commerce"
  - "Secretary of Commerce"

api_keywords:
  - "Howard Lutnick"
  - "Department of Commerce"

rss_feeds:
  foxnews: https://feeds.foxnews.com/foxnews/latest
  wsj: https://feeds.content.dowjones.io/public/rss/socialpoliticsfeed
  washingtonpost: https://feeds.washingtonpost.com/rss/politics
  politico: https://rss.politico.com/politics-news.xml
  nytimes: https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml
  bloomberg: https://feeds.bloomberg.com/politics/news.rss
  financialtimes: https://www.ft.com/?format=rss
  cnbc: https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10000113
  cnn: http://rss.cnn.com/rss/cnn_allpolitics.rss
  abc: https://abcnews.go.com/abcnews/politicsheadlines
  bbc: https://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml
  foxbusiness: https://feeds.foxbusiness.com/foxbusiness/latest
